"""
Email Templates - HTML versions with direct reply/call CTAs
No Calendly — just reply or call. Zero friction, zero dependencies.

Touch 1: Initial Strike (compliance hook)
Touch 2: Day 3 Follow-up (value add)
Touch 3: Day 7 Final Push (urgency + foot-in-door)
Touch 4: Reply Auto-Response (warm + book call)
Touch 5: Post-Call Follow-up (agreement + Stripe link)
"""

BASE_STYLE = """
<style>
  body { margin: 0; padding: 0; background: #f5f5f5; font-family: 'Helvetica Neue', Arial, sans-serif; }
  .wrapper { max-width: 600px; margin: 0 auto; background: #ffffff; }
  .header { background: #0a0a1a; padding: 32px 40px; }
  .header h1 { color: #ffffff; font-size: 20px; margin: 0; letter-spacing: 2px; font-weight: 300; }
  .header span { color: #e8b84b; font-weight: 700; }
  .body { padding: 40px; }
  .body p { color: #333; font-size: 15px; line-height: 1.7; margin: 0 0 16px; }
  .risk-box { background: #fff5f5; border-left: 4px solid #e53e3e; padding: 20px 24px; margin: 24px 0; border-radius: 4px; }
  .risk-box p { margin: 0 0 6px; color: #c53030; font-weight: 600; font-size: 14px; }
  .value-box { background: #f0fff4; border-left: 4px solid #38a169; padding: 20px 24px; margin: 24px 0; border-radius: 4px; }
  .value-box p { margin: 0 0 6px; color: #276749; font-size: 14px; }
  .cta-primary { display: inline-block; background: #e8b84b; color: #0a0a1a; padding: 16px 36px; border-radius: 4px; text-decoration: none; font-weight: 700; font-size: 15px; letter-spacing: 1px; margin: 24px 0 8px; }
  .cta-secondary { display: inline-block; background: transparent; color: #0a0a1a; padding: 14px 32px; border-radius: 4px; text-decoration: none; font-weight: 600; font-size: 14px; border: 2px solid #0a0a1a; margin: 8px 0 24px; }
  .divider { border: none; border-top: 1px solid #eee; margin: 32px 0; }
  .footer { background: #f9f9f9; padding: 24px 40px; border-top: 1px solid #eee; }
  .footer p { color: #999; font-size: 12px; margin: 0 0 4px; line-height: 1.6; }
  .badge { display: inline-block; background: #0a0a1a; color: #e8b84b; padding: 4px 10px; border-radius: 2px; font-size: 11px; font-weight: 700; letter-spacing: 1px; margin-bottom: 16px; }
</style>
"""

def touch_1_strike(name: str, risk_score: int, reply_email: str, phone: str,
                   bill96_issues: list = None) -> dict:
    """Initial cold outreach — compliance hook"""
    issues_html = ""
    if bill96_issues:
        issues_html = "".join([f"<p>⚠️ {i}</p>" for i in bill96_issues])
    else:
        issues_html = "<p>⚠️ English-only digital presence detected</p><p>⚠️ No French language policy page found</p><p>⚠️ OQLF compliance gap: HIGH</p>"

    html = f"""<!DOCTYPE html><html><head><meta charset="UTF-8">{BASE_STYLE}</head><body>
<div class="wrapper">
  <div class="header"><h1>NORTHERN <span>VENTURES</span></h1></div>
  <div class="body">
    <span class="badge">INTELLIGENCE REPORT</span>
    <p>Bonjour {name},</p>
    <p>Our Cyber-Hounds completed a digital sovereignty audit on your firm. You flagged at <strong>{risk_score}/10</strong> for Bill 96 compliance risk — that's in the top tier of exposure we're currently tracking across Quebec.</p>
    <div class="risk-box">
      <p>🔴 CRITICAL FLAGS IDENTIFIED:</p>
      {issues_html}
    </div>
    <p>The OQLF has increased enforcement activities in Q1 2026. A single violation carries fines up to <strong>$30,000 CAD</strong> — and that's before the reputational damage of being named publicly.</p>
    <p>We've prepared a full 5-page compliance audit specific to your firm. Reply to this email and I'll send it immediately — then we can schedule a 15-minute call to walk through it together.</p>
    <div style="text-align:center; padding: 8px 0;">
      <a href="mailto:{reply_email}?subject=Re: Bill 96 Audit Request — {name}" class="cta-primary">✉️ REPLY TO GET YOUR FREE AUDIT</a><br/>
      <a href="tel:{phone.replace(' ','').replace('-','')}" class="cta-secondary">📞 Call Us: {phone}</a>
    </div>
    <hr class="divider"/>
    <p style="font-size:13px; color:#666;">We also offer an autonomous AI solution that generates Bill 96-compliant Quebec French creative at 100x the speed of a traditional agency — at 90% lower cost. But compliance first.</p>
  </div>
  <div class="footer">
    <p><strong>Bee — Northern Ventures Intelligence Division</strong></p>
    <p>This report was generated by our Cyber-Hound scanning system and is confidential to your organization.</p>
  </div>
</div></body></html>"""

    return {
        "subject": f"⚠️ Bill 96 Risk Alert: {name} — {risk_score}/10 Exposure Score",
        "html": html,
        "touch": 1
    }


def touch_2_followup(name: str, reply_email: str, phone: str) -> dict:
    """Day 3 follow-up — value add, no pressure"""
    html = f"""<!DOCTYPE html><html><head><meta charset="UTF-8">{BASE_STYLE}</head><body>
<div class="wrapper">
  <div class="header"><h1>NORTHERN <span>VENTURES</span></h1></div>
  <div class="body">
    <span class="badge">FOLLOW-UP</span>
    <p>Bonjour {name},</p>
    <p>I sent you our compliance alert earlier this week. Wanted to add some context before I follow up again.</p>
    <div class="value-box">
      <p>✅ 3 things your competitors are doing right now:</p>
      <p>1. Publishing a bilingual <em>Politique de confidentialité</em> (Law 25 requirement)</p>
      <p>2. Running French-language Meta ad variants targeting Montreal & Quebec City</p>
      <p>3. Displaying French as the default language on all Quebec-targeted landing pages</p>
    </div>
    <p>Quebec is 8.5 million French-speaking consumers. When they see an English-only brand, they scroll. That's the market you're currently leaving on the table.</p>
    <p>Just hit reply — I'll send the full audit PDF and we can find 15 minutes that work for you.</p>
    <div style="text-align:center; padding: 8px 0;">
      <a href="mailto:{reply_email}?subject=Re: Bill 96 Follow-Up — {name}" class="cta-primary">✉️ REPLY TO REQUEST THE FULL AUDIT</a><br/>
      <a href="tel:{phone.replace(' ','').replace('-','')}" class="cta-secondary">📞 {phone}</a>
    </div>
  </div>
  <div class="footer">
    <p><strong>Bee — Northern Ventures Intelligence Division</strong></p>
  </div>
</div></body></html>"""

    return {
        "subject": f"Re: Bill 96 Alert — One thing worth seeing, {name}",
        "html": html,
        "touch": 2
    }


def touch_3_final(name: str, reply_email: str, phone: str,
                  audit_price: str = "$750 CAD") -> dict:
    """Day 7 final push — foot-in-door offer"""
    retainer_price = audit_price.replace("750", "3,500")
    html = f"""<!DOCTYPE html><html><head><meta charset="UTF-8">{BASE_STYLE}</head><body>
<div class="wrapper">
  <div class="header"><h1>NORTHERN <span>VENTURES</span></h1></div>
  <div class="body">
    <span class="badge">FINAL NOTICE</span>
    <p>Bonjour {name},</p>
    <p>Last message from me on this — I don't want to be noise in your inbox.</p>
    <p>Two options. You pick:</p>
    <div class="value-box">
      <p><strong>Option A — Full Retainer ({retainer_price}/mo)</strong></p>
      <p>Weekly AI-generated Quebec French creatives, Bill 96 compliance on every asset, autonomous Meta optimization, monthly intelligence report.</p>
    </div>
    <div class="risk-box">
      <p><strong>Option B — Start with the Audit ({audit_price})</strong></p>
      <p>We identify every compliance gap. You see our quality. No commitment beyond the audit. If you don't love the work, it ends there.</p>
    </div>
    <p>One OQLF fine covers 40 months of Option B. The math isn't complicated.</p>
    <p>Just reply with "A" or "B" and I'll take it from there.</p>
    <div style="text-align:center; padding: 8px 0;">
      <a href="mailto:{reply_email}?subject=Option A — {name}&body=I'm interested in Option A (Retainer)" class="cta-primary">✉️ OPTION A — FULL RETAINER</a><br/>
      <a href="mailto:{reply_email}?subject=Option B — {name}&body=I'd like to start with the $750 audit" class="cta-secondary">✉️ Option B — Start with the Audit</a>
    </div>
    <p style="font-size:13px; color:#999; text-align:center;">After this I'll set a 6-month reminder and reach out again when the regulatory landscape shifts further.</p>
  </div>
  <div class="footer">
    <p><strong>Bee — Northern Ventures Intelligence Division</strong></p>
    <p>Northern Ventures | Montreal, Quebec | {phone}</p>
  </div>
</div></body></html>"""

    return {
        "subject": f"Last message: Option A or B — your call, {name}",
        "html": html,
        "touch": 3
    }


def touch_4_reply_autoresponse(name: str, reply_email: str, phone: str) -> dict:
    """Auto-response when watchdog detects a reply — fires within 5 minutes"""
    html = f"""<!DOCTYPE html><html><head><meta charset="UTF-8">{BASE_STYLE}</head><body>
<div class="wrapper">
  <div class="header"><h1>NORTHERN <span>VENTURES</span></h1></div>
  <div class="body">
    <span class="badge">GOT YOUR MESSAGE</span>
    <p>Bonjour {name},</p>
    <p>Got your reply — thank you. I'll be back in touch personally within the hour.</p>
    <p>If you'd like to move faster, call me directly and we can sort everything in 15 minutes:</p>
    <div style="text-align:center; padding: 8px 0;">
      <a href="tel:{phone.replace(' ','').replace('-','')}" class="cta-primary">📞 CALL NOW: {phone}</a><br/>
      <a href="mailto:{reply_email}" class="cta-secondary">✉️ Or keep the conversation by email</a>
    </div>
    <p>The call covers:</p>
    <ul style="color:#333; font-size:15px; line-height:2;">
      <li>Your exact Bill 96 / Law 25 exposure points</li>
      <li>Live demo of AI-generated Quebec French creative</li>
      <li>The exact package that fits your situation</li>
    </ul>
    <p>Talk soon.</p>
  </div>
  <div class="footer">
    <p><strong>Bee — Northern Ventures Intelligence Division</strong></p>
  </div>
</div></body></html>"""

    return {
        "subject": f"Re: Got your message — call me directly, {name}",
        "html": html,
        "touch": 4
    }


def touch_5_post_call(name: str, offer: str, stripe_link: str, reply_email: str) -> dict:
    """Post-call follow-up — agreement + Stripe payment link"""
    html = f"""<!DOCTYPE html><html><head><meta charset="UTF-8">{BASE_STYLE}</head><body>
<div class="wrapper">
  <div class="header"><h1>NORTHERN <span>VENTURES</span></h1></div>
  <div class="body">
    <span class="badge">POST-CALL SUMMARY</span>
    <p>Bonjour {name},</p>
    <p>Great speaking with you. As promised — everything to move forward is right here:</p>
    <div class="value-box">
      <p><strong>Selected Package: {offer}</strong></p>
      <p>✅ First deliverable within 72 hours of payment</p>
      <p>✅ Bill 96 compliance audit included in Month 1</p>
      <p>✅ Month-to-month — cancel anytime</p>
    </div>
    <div style="text-align:center; padding: 16px 0;">
      <a href="{stripe_link}" class="cta-primary">💳 COMPLETE PAYMENT — ACTIVATE YOUR ACCOUNT</a>
    </div>
    <p style="font-size:13px; color:#666; text-align:center;">Secure payment via Stripe. Receipt sent immediately. Work begins within 72 hours.</p>
    <hr class="divider"/>
    <p>Questions? Just reply to this email.</p>
  </div>
  <div class="footer">
    <p><strong>Bee — Northern Ventures Intelligence Division</strong></p>
    <p>Northern Ventures | Montreal, Quebec | <a href="mailto:{reply_email}" style="color:#999;">{reply_email}</a></p>
  </div>
</div></body></html>"""

    return {
        "subject": f"Your Northern Ventures Package — Payment Link Inside, {name}",
        "html": html,
        "touch": 5
    }
