-- CyberHound Colony OS — Database Schema
-- Migration: 001_cyberhound_schema
-- Created: 2026-03-21

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- OPPORTUNITIES
-- Discovered by Scout Bee, approved/vetoed by HITL
-- ============================================================
CREATE TABLE IF NOT EXISTS opportunities (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  niche TEXT NOT NULL,
  market TEXT NOT NULL DEFAULT 'North America',
  description TEXT NOT NULL DEFAULT '',
  score INTEGER NOT NULL DEFAULT 0 CHECK (score >= 0 AND score <= 100),
  status TEXT NOT NULL DEFAULT 'discovered'
    CHECK (status IN ('discovered', 'pending_approval', 'approved', 'rejected', 'building', 'live', 'archived')),
  scout_data JSONB NOT NULL DEFAULT '{}',
  queen_reasoning TEXT,
  approved_at TIMESTAMPTZ,
  rejected_at TIMESTAMPTZ,
  rejection_reason TEXT,
  campaign_id UUID
);

-- ============================================================
-- CAMPAIGNS
-- Built by Builder Bee after opportunity approval
-- ============================================================
CREATE TABLE IF NOT EXISTS campaigns (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  name TEXT NOT NULL,
  opportunity_id UUID REFERENCES opportunities(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'idle'
    CHECK (status IN ('idle', 'hunting', 'building', 'closing', 'paused')),
  landing_page_url TEXT,
  stripe_product_id TEXT,
  stripe_price_id TEXT,
  stripe_payment_link TEXT,
  mrr INTEGER NOT NULL DEFAULT 0, -- in cents
  customer_count INTEGER NOT NULL DEFAULT 0,
  target_mrr INTEGER NOT NULL DEFAULT 0 -- in cents
);

-- ============================================================
-- ASSETS
-- Landing pages, email sequences, copy generated by Builder
-- ============================================================
CREATE TABLE IF NOT EXISTS assets (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  campaign_id UUID REFERENCES campaigns(id) ON DELETE CASCADE,
  type TEXT NOT NULL
    CHECK (type IN ('landing_page', 'email_sequence', 'stripe_product', 'copy')),
  content JSONB NOT NULL DEFAULT '{}',
  url TEXT,
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'live', 'archived'))
);

-- ============================================================
-- OUTREACH LOG
-- Emails and messages sent by Closer Bee
-- ============================================================
CREATE TABLE IF NOT EXISTS outreach_log (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  campaign_id UUID REFERENCES campaigns(id) ON DELETE CASCADE,
  channel TEXT NOT NULL CHECK (channel IN ('email', 'telegram', 'linkedin')),
  recipient TEXT NOT NULL,
  subject TEXT,
  body TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued', 'sent', 'opened', 'replied', 'converted', 'bounced')),
  sent_at TIMESTAMPTZ,
  opened_at TIMESTAMPTZ,
  replied_at TIMESTAMPTZ
);

-- ============================================================
-- REVENUE EVENTS
-- Stripe webhook events tracked by Treasurer Bee
-- ============================================================
CREATE TABLE IF NOT EXISTS revenue_events (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  campaign_id UUID REFERENCES campaigns(id) ON DELETE SET NULL,
  stripe_event_id TEXT NOT NULL UNIQUE,
  event_type TEXT NOT NULL,
  amount INTEGER NOT NULL DEFAULT 0, -- in cents
  currency TEXT NOT NULL DEFAULT 'usd',
  customer_email TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'
);

-- ============================================================
-- HIVE LOG
-- Full audit trail of all bee actions
-- ============================================================
CREATE TABLE IF NOT EXISTS hive_log (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  bee TEXT NOT NULL CHECK (bee IN ('queen', 'scout', 'builder', 'closer', 'treasurer')),
  action TEXT NOT NULL,
  details JSONB NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'success'
    CHECK (status IN ('success', 'error', 'pending_approval', 'vetoed')),
  telegram_message_id TEXT
);

-- ============================================================
-- HITL APPROVALS
-- Human-in-the-loop approval queue — Brandon's veto system
-- ============================================================
CREATE TABLE IF NOT EXISTS hitl_approvals (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  hive_log_id UUID REFERENCES hive_log(id) ON DELETE CASCADE,
  action_type TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'vetoed')),
  decided_at TIMESTAMPTZ,
  telegram_message_id TEXT
);

-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_opportunities_status ON opportunities(status);
CREATE INDEX IF NOT EXISTS idx_campaigns_status ON campaigns(status);
CREATE INDEX IF NOT EXISTS idx_hive_log_bee ON hive_log(bee);
CREATE INDEX IF NOT EXISTS idx_hive_log_created ON hive_log(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_hitl_approvals_status ON hitl_approvals(status);
CREATE INDEX IF NOT EXISTS idx_revenue_events_stripe ON revenue_events(stripe_event_id);

-- ============================================================
-- UPDATED_AT TRIGGER
-- ============================================================
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER opportunities_updated_at
  BEFORE UPDATE ON opportunities
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER campaigns_updated_at
  BEFORE UPDATE ON campaigns
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================
ALTER TABLE opportunities ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE outreach_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE revenue_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE hive_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE hitl_approvals ENABLE ROW LEVEL SECURITY;

-- Service role has full access (used by API routes)
-- Anon role has read-only access to non-sensitive tables
CREATE POLICY "service_full_access_opportunities" ON opportunities
  FOR ALL USING (true);

CREATE POLICY "service_full_access_campaigns" ON campaigns
  FOR ALL USING (true);

CREATE POLICY "service_full_access_hive_log" ON hive_log
  FOR ALL USING (true);

CREATE POLICY "service_full_access_hitl_approvals" ON hitl_approvals
  FOR ALL USING (true);

CREATE POLICY "service_full_access_assets" ON assets
  FOR ALL USING (true);

CREATE POLICY "service_full_access_outreach_log" ON outreach_log
  FOR ALL USING (true);

CREATE POLICY "service_full_access_revenue_events" ON revenue_events
  FOR ALL USING (true);
